{
 "title": "HiveMQ Cluster V2",
 "tags": [ "mqtt" ],
 "time": { "from": "2021-08-14T13:02:37.128Z", "to": "2021-08-15T07:10:34.753Z" },
 "templating": {
  "list": [
   {
    "name": "diskdevice",
    "query": "nvme1n1,sda,vda,hda,nvme1n1,nvme0n1"
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(com_hivemq_messages_incoming_connect_count, deployment)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(com_hivemq_messages_incoming_connect_count, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Used %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu.total - $tag_node",
     "expr": "com_hivemq_system_os_global_cpu_total_total",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} cpu.total",
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_guest\")  + mean(\"usage_guest_nice\") + mean(\"usage_iowait\") + mean(\"usage_irq\") + mean(\"usage_nice\") + mean(\"usage_softirq\") + mean(\"usage_steal\") + mean(\"usage_system\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Memory Used %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "mem.total - $tag_node",
     "expr": "com_hivemq_system_os_global_memory_total - com_hivemq_system_os_global_memory_available",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} mem.used",
     "measurement": "mem",
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_guest\")  + mean(\"usage_guest_nice\") + mean(\"usage_iowait\") + mean(\"usage_irq\") + mean(\"usage_nice\") + mean(\"usage_softirq\") + mean(\"usage_steal\") + mean(\"usage_system\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "com_hivemq_system_os_global_memory_total",
     "legendFormat": "{{hostname}} mem.total"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "com_hivemq_jvm_memory_heap_max", "legendFormat": "{{hostname}} heap.max" },
    {
     "expr": "com_hivemq_jvm_memory_heap_init",
     "legendFormat": "{{hostname}} heap.init"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} heap.used",
     "measurement": "com.hivemq.jvm.memory.heap.used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_system_os_process_memory_resident_set_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} memory-resident",
     "measurement": "com.hivemq.system.os.process.memory.resident-set-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_cluster_nodes_count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Cluster nodes",
     "measurement": "com.hivemq.cluster.nodes.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Single Writer Tasks Total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_total_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Connections (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connections - $tag_host",
     "expr": "com_hivemq_networking_connections_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} connections",
     "measurement": "com.hivemq.networking.connections.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Messages (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Network Bytes Received - $tag_node",
     "expr": "com_hivemq_messages_queued_count",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} queued messages",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dropped Messages by Reason (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "before-publish-send - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_publish_inbound_intercepted_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} publish-inbound-intercepted",
     "measurement": "com.hivemq.messages.dropped.before-publish-send.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "inflight-window-full - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_message_too_large_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} message-too-large",
     "measurement": "com.hivemq.messages.dropped.in-flight-window.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "internal-error - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_not_writable_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} not-writable",
     "measurement": "com.hivemq.messages.dropped.internal-error.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "not-connected - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_qos_0_memory_exceeded_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} qos0-memory-exceeded",
     "measurement": "com.hivemq.messages.dropped.not-connected.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "not-writeable - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_queue_full_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} queue-full",
     "measurement": "com.hivemq.messages.dropped.not-writable.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "qos0-queue-not-empty - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_internal_error_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} internal-error",
     "measurement": "com.hivemq.messages.dropped.qos-0-queue-not-empty.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Sessions (1m, stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MQTT Sessions - $tag_host",
     "expr": "com_hivemq_sessions_overall_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} MQTT Sessions",
     "measurement": "com.hivemq.sessions.overall.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Members GMS (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MQTT Sessions - $tag_host",
     "expr": "com_hivemq_cluster_internal_gms_num_members",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Members GMS",
     "measurement": "com.hivemq.sessions.overall.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Level",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Overload Protection level - $tag_host",
     "expr": "com_hivemq_overload_protection_level",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Overload Protection level",
     "measurement": "com.hivemq.overload-protection.level",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONNECT (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "connect.rate - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_connect_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} connect.rate",
     "measurement": "com.hivemq.messages.incoming.connect.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUBLISH incoming (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "publish.incoming - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_publish_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} publish.incoming",
     "measurement": "com.hivemq.messages.incoming.publish.count",
     "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUBLISH outgoing (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "publish.outgoing - $tag_host",
     "expr": "delta(com_hivemq_messages_outgoing_publish_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} publish.outgoing",
     "measurement": "com.hivemq.messages.outgoing.publish.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Subscriptions (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "subscribe.count - $tag_host",
     "expr": "com_hivemq_subscriptions_overall_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} subscribe.count",
     "measurement": "com.hivemq.subscriptions.overall.current",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network In/Out (1s rate)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Network Bytes Sent - $tag_node",
     "expr": "irate(com_hivemq_system_os_network_interface_eth0_bytes_sent[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Bytes Sent",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Network Bytes Sent - $tag_node",
     "expr": "-1 * irate(com_hivemq_system_os_network_interface_eth0_bytes_received[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Bytes Received",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Requests Sent (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$4 - $tag_host",
     "expr": "delta(label_replace({ __name__=~\"com_hivemq_cluster_sent_.*\"}, \"request\", \"$1\", \"__name__\", \"com_hivemq_cluster_sent_(.*)?_total\")[1m:1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{request}} - {{hostname}}",
     "measurement": "/com.hivemq.cluster.sent.*/",
     "query": "SELECT difference(mean(\"count\")) FROM /com.hivemq.cluster.sent.*/ WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Closed Connections (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "closed_connections.rate - $tag_host",
     "expr": "delta(com_hivemq_networking_connections_closed_total_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} closed_connections.rate",
     "measurement": "com.hivemq.networking.connections-closed.total.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$4 - $tag_host",
     "expr": "com_hivemq_messages_retained_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ hostname }}",
     "measurement": "/com.hivemq.cluster.sent.*/",
     "query": "SELECT difference(mean(\"count\")) FROM /com.hivemq.cluster.sent.*/ WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka to MQTT polled (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$4 - $tag_host",
     "expr": "delta(label_replace({__name__=~\"kafka_extension_kafka_to_mqtt_transformer_.*_polled_record_count\", deployment=\"$deployment\", job=\"$job\"}, \"transformer\", \"$1\", \"__name__\", \"kafka_extension_kafka_to_mqtt_transformer_(.*)?_polled_record_count\")[1m:1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ pod }} - {{ transformer }}",
     "measurement": "/com.hivemq.cluster.sent.*/",
     "query": "SELECT difference(mean(\"count\")) FROM /com.hivemq.cluster.sent.*/ WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Time (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "MQTT Sessions - $tag_host",
     "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Young_Generation_time[1m]) + delta(com_hivemq_jvm_garbage_collector_G1_Old_Generation_time[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} GC Time",
     "measurement": "com.hivemq.sessions.overall.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Bytes Read/Write (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Bytes Read - $tag_node",
     "expr": "delta(com_hivemq_system_os_disks__dev_xvda_read_bytes[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Disk Bytes Read",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Disk Bytes Write - $tag_node",
     "expr": "- delta(com_hivemq_system_os_disks__dev_xvda_write_bytes[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Disk Bytes Write",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT packets incoming (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "mqtt.incoming - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_total_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} messages.incoming",
       "measurement": "com.hivemq.messages.incoming.total.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "MQTT packets outgoing (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "mqtt.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_total_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} messages.outgoing",
       "measurement": "com.hivemq.messages.outgoing.total.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "CONNECT in (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_connect_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} connect incoming",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "CONNACK out (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_connack_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} subscribe incoming",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "SUBSCRIBE in (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_subscribe_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} subscribe incoming",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "SUBACK out (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_suback_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} suback outgoing",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PUBLISH incoming (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "publish.incoming - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_publish_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} publish.incoming",
       "measurement": "com.hivemq.messages.incoming.publish.count",
       "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PUBACK out (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_puback_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} subscribe incoming",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PUBLISH outgoing (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "publish.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_publish_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} publish.outgoing",
       "measurement": "com.hivemq.messages.outgoing.publish.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PUBACK in (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.outgoing - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_puback_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} subscribe incoming",
       "measurement": "com.hivemq.messages.outgoing.pingresp.count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PING incoming (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.incoming - $tag_host",
       "expr": "delta(com_hivemq_messages_incoming_pingreq_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} ping.incoming",
       "measurement": "com.hivemq.messages.incoming.pingreq.count",
       "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PING outgoing (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ping.incoming - $tag_host",
       "expr": "delta(com_hivemq_messages_outgoing_pingresp_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}} ping.incoming",
       "measurement": "com.hivemq.messages.incoming.pingreq.count",
       "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Young Gen (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Young_Generation_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} GC Young Gen",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Young Gen Time (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Young_Generation_time[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} GC Young Gen",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Old Gen (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Old_Generation_count[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}}  GC Old Gen",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Old Gen Time (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Old_Generation_time[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} GC Old Gen ",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_jvm_threads_count",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "com.hivemq.jvm.threads.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Blocked Threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_jvm_threads_blocked_count",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "com.hivemq.jvm.threads.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes In (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Received - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_bytes_received[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Bytes Received",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Bytes Out (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Sent - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_bytes_sent[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Bytes Sent",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Errors In  (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Sent - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_in_errors[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Errors In",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Errors Out  (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Sent - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_out_errors[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Errors Out",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets Rcv  (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Sent - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_packets_received[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Packets Received",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets Sent  (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Sent - $tag_node",
       "expr": "delta(com_hivemq_system_os_network_interface_eth0_packets_sent[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Network Packets Sent",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Single Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Attribute Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_attribute_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Event Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_client_events_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Session Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_client_session_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Message Flow Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_incoming_message_flow_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Messages Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_queued_messages_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Eventbus Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_request_event_bus_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retained Messages Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_retained_messages_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Subscription Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_subscription_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topic Tree Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_persistence_executor_topic_tree_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extension Executor Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_extension_task_executors_queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}}",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Single Writer Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Attribute Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_attribute_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client Events Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_client_events_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client Session Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_client_session_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Incoming Message Flow Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_incoming_message_flow_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Queued Messages Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_queued_messages_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Eventbus Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_request_event_bus_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Retained Messages Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_retained_messages_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Subscription Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_subscription_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Topic Tree Times (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_topic_tree_time{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Overall Sampled Duration (p999)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_persistence_executor_sampled_duration{quantile=\"0.999\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "legendFormat": "{{hostname}}",
       "measurement": "/com.hivemq.persistence.executor.*.tasks/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "FD Suspected Events (1m, stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "com_hivemq_cluster_internal_fd_num_suspect_events_generated",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} FD Suspected Events",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FD Sock Suspected Events (1m, stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "com_hivemq_cluster_internal_fd_sock_num_suspect_events_generated",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} FD Suspected Events",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP Bundler Size (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "retained-messages - $tag_host",
       "expr": "com_hivemq_cluster_internal_transport_bundler_buffer_size",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} bundler-size",
       "measurement": "com.hivemq.messages.retained.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "JGroups received (1m, stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "delta(com_hivemq_cluster_internal_transport_num_msgs_received[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} FD Suspected",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jgroups Messages (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Network Bytes Received - $tag_node",
       "expr": "delta(com_hivemq_cluster_internal_transport_num_msgs_sent[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} jgroups messages",
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cluser Transport Batch size (1m, stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "MQTT Sessions - $tag_host",
       "expr": "com_hivemq_cluster_internal_transport_average_batch_size",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} Transport Batch Size",
       "measurement": "com.hivemq.sessions.overall.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jgroups Missing/Unacked (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_hivemq_cluster_internal_unicast3_xmit_table_missing_messages",
       "legendFormat": "{{hostname}} missing unicast"
      },
      {
       "expr": "- com_hivemq_cluster_internal_unicast3_num_unacked_messages",
       "legendFormat": "{{hostname}} unacked unicast"
      }
     ]
    },
    {
     "title": "Jgroups Retry (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(com_hivemq_cluster_internal_unicast3_num_xmits[1m])",
       "legendFormat": "{{hostname}} retry unicast"
      }
     ]
    },
    {
     "title": "Not Responsible (stacked, 1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "not_responsible - $tag_host",
       "expr": "delta(com_hivemq_cluster_internal_response_not_responsible[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} not_responsible",
       "measurement": "com.hivemq.cluster.internal.response.not-responsible",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client Connected Sent (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$4 - $tag_host",
       "expr": "rate(com_hivemq_cluster_sent_ClientConnectedRequest_total[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ pod }} connected requests",
       "measurement": "/com.hivemq.cluster.sent.*/",
       "query": "SELECT difference(mean(\"count\")) FROM /com.hivemq.cluster.sent.*/ WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client Disconnected Sent (1m)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$4 - $tag_host",
       "expr": "rate(com_hivemq_cluster_sent_ClientDisconnectedRequest_total[1m])",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ pod }} disconnected requests",
       "measurement": "/com.hivemq.cluster.sent.*/",
       "query": "SELECT difference(mean(\"count\")) FROM /com.hivemq.cluster.sent.*/ WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connect Queues (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "retained-messages - $tag_host",
       "expr": "com_hivemq_internal_connect_request_queue_amount",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{hostname}} connect queues",
       "measurement": "com.hivemq.messages.retained.current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Overload Protection Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Overload Protected Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_global_tasks",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} global tasks",
     "measurement": "/com.hivemq.persistence.executor.*.tasks/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OP Backpressure Active (stacked, max, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Active backpressure - $tag_host",
     "expr": "com_hivemq_overload_protection_clients_backpressure_active",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Active backpressure",
     "measurement": "com.hivemq.overload-protection.clients.backpressure-active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OP Using Credits (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Using Credits - $tag_host",
     "expr": "com_hivemq_overload_protection_clients_using_credits",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Using Credits",
     "measurement": "com.hivemq.overload-protection.clients.using-credits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OP Credits per tick (10s)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_credits_per_tick",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "com.hivemq.overload-protection.credits.per-tick",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OP avg Credits (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_clients_average_credits",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}} Average Credits",
     "measurement": "com.hivemq.overload-protection.clients.average-credits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OP Execution duration (0.99 percentile, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Execution duration - $tag_host",
     "expr": "com_hivemq_supervision_scheduled_executor_duration{quantile=\"0.999\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Execution duration",
     "measurement": "com.hivemq.supervision.scheduled-executor.duration",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Level",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Overload Protection level - $tag_host",
     "expr": "com_hivemq_overload_protection_level",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{hostname}} Overload Protection level",
     "measurement": "com.hivemq.overload-protection.level",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}