version: "3.5"

services:
  nginx:
    image: docker.io/nginxinc/nginx-unprivileged:1.25.4-alpine
    container_name: nginx
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tutorials

networks:
  tutorials:
    name: tutorials
    driver: bridge
