services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - .:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - tutorials

volumes:
  prom_data:

networks:
  tutorials:
    external: true
