global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: mongodb
    static_configs:
      - targets: ["mongo-exporter:9216"]
  - job_name: "weather-service"
    metrics_path: "/metrics"
    scheme: http
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["weather-service:9090"]
  - job_name: "sensor-service"
    metrics_path: "/metrics"
    scheme: http
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["sensor-service:9090"]
